services:
  # Runs the bot
  bot:
    build: 
      dockerfile: Containerfile.client
    
    volumes:
      - .:/home/appuser/app:Z
    env_file:
      - env.ini
    restart: always
    tty: true

    networks:
      - rbnet
    ports:
    - 5679:5678
  # Redis service for caching
  redis:
    image: redis:latest
    networks:
      - rbnet
  


networks:
  rbnet:
    driver: bridge